name: budgetking

services:
  # Base de Datos impecable y centralizada
  db:
    image: mysql:8.0
    container_name: budget-db
    restart: always
    environment:
      MYSQL_DATABASE: budget_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user_budget
      MYSQL_PASSWORD: user_password
    ports:
      # MAPEAMOS EL PUERTO HACIA AFUERA: Tu Windows ahora puede ver la BD en el 3306
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    # Reemplazá tu bloque de healthcheck por este:
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  db_data: