services:
  - type: web
    name: budgetking-backend
    runtime: docker
    plan: free
    dockerfilePath: ./BudgetKing/Dockerfile
    dockerContext: ./BudgetKing
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: JWT_SECRET
        sync: false
